Milestone 2
vzdrizhni/Calculator pull request #2
Opened 2020-08-12 14:11 UTC by vzdrizhni

- Added: App, Display, ButtonPanel, and Button components.

2020-08-13 12:08 UTC, fatymahmed requested changes
## Hi @vzdrizhni  
You have done a great job on this milestone 👏👏
However, there are some things that we need to fix.
**Kindly check my comments below**

## Status: Changes Required ♻️
_Feel free to reach out to me on slack (Fatima) if you have any questions or need any help_

2020-08-13 12:10 UTC, fatymahmed commented on README.md
> +  > to be added
- Add more information about the project here, even though it is still being developed, you already know that this is a calculator project see [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)

2020-08-13 12:16 UTC, fatymahmed commented on src/components/App.js
> +  }
- Why are you setting the result to `0` here?, remember that this should be a functional component as mentioned on Pathwright, see [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone2/app/appFunctionalComponent.png), therefore you do not need the constructor part rather you should only render the `Display` and `ButtonPanel` components in a `div`

2020-08-13 12:22 UTC, fatymahmed commented on src/components/button.component.jsx
> +    </div>
- This component should accept the `button name` as an incoming prop  [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone2/button/acceptProp.png) which should be of type `String` [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone2/button/validateAsString.png)

2020-08-13 12:26 UTC, fatymahmed commented on src/components/display.component.jsx
> +
- You should set the type of the `result` prop as `String` here see [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone2/display/validateAsString.png)
  and the default value which will be `'0'` see [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone2/display/DefaultProp.png)

2020-08-17 06:02 UTC, Oghenebrume50 requested changes
### CHANGES REQUIRED

Hi @vzdrizhni good job making changes as outlined by the previous reviewer, everything thing seems to be in order but you need to properly use PropTypes to validate the props being passed to different components. This is why you were advised to add propTypes to the project in the first milestone

**Please make changes and request for another review** :slightly_smiling_face: 

**RAPHAEL NORIODE** :mask: STAY_SAFE

2020-08-17 06:02 UTC, Oghenebrume50 commented on src/components/button.component.jsx
> +export default Button
Use proptypes package to validate that the datatype of the prop being received here

2020-08-17 06:02 UTC, Oghenebrume50 commented on src/components/display.component.jsx
> +
Use proptypes package to validate that the datatype of the prop being received here

2020-08-17 08:16 UTC, vzdrizhni commented
Changes required by TSE made:
- Use proptypes package to validate that the datatype of the prop.
- Added default prop to Display component.

2020-08-17 10:35 UTC, Oghenebrume50 approved these changes
### APPROVED

Hi @vzdrizhni this looks good :+1: kudos on making changes as earlier requested please merge and move on **This is approved**


**RAPHAEL NORIODE** :mask: STAY_SAFE

2020-08-17 13:37 UTC, merged