Milestone 5
vzdrizhni/Calculator pull request #6
Opened 2020-08-19 15:56 UTC by vzdrizhni

- Added handleClick function to complete the project.

2020-08-19 18:58 UTC, shloch requested changes
## Hello @vzdrizhni , 

![calc](https://user-images.githubusercontent.com/40712459/90678024-1116e780-e256-11ea-8837-96d831ef9b2b.gif)

I stopped at MVP testing phase, because at `milestone 5`, the app should actually work
so I tried to solve `3 + 2`, it rendered `34`

Please make this work (addition, substration, multiplication, division, etc..)

Let's get to debugging....

Happy coding

2020-08-20 07:24 UTC, vzdrizhni commented
Fixed the bug.

2020-08-20 19:16 UTC, shloch approved these changes
## Hello  @vzdrizhni 

Great job, this works smoothly this time............keep up with the good work

### [optional changes]
- You can center the calculator with `margin:auto`
![Screen Shot 2020-08-20 at 7 55 04 PM](https://user-images.githubusercontent.com/40712459/90813250-3a4f7a80-e31f-11ea-95d8-4a712af0be05.png)

YOU GET A THUMBS UP.......but Checkout the comment below

Happy coding

2020-08-20 19:16 UTC, shloch commented on src/logic/operate.js
> +        total = 0;
`total` should be equal to `Error` or `NaN`...something like that
(`if num2 == 0`)

Also while disable this `===` operator ?

2020-08-20 19:31 UTC, vzdrizhni commented on src/logic/operate.js
> +        total = 0;
Thanks for your review. To be honest, I already don't remember why I did it, but I remember that there should be a reason. 😄

2020-08-21 08:08 UTC, merged